### ISSUE TITLE
Not accurate (lol)

### ISSUE THREAD

**Issue by Max-xoxo** [ds5678/Better-Night-Sky#1]
Where is da milky wae?

**Comment by ds5678** [comment]
Seriously?

**Comment by Max-xoxo** [comment]
Not entirely seriously, but also didn't say it entirely without a reason.
To be entirely honest and serious this time, I just want to ask, would you be interested in replacing the current night sky texture  from the mod with a more accurate recreation of the night sky in the far northern hemisphere, with the milky way clearly visible, like it would be in an almost light unpolluted area like the Great Bear is, if provided with such texture?

Apologies for making a proper suggestion sound so dumb, my bad. The memer instinct just got the better of me.

**Comment by ds5678** [comment]
Although I'm not opposed to the idea of improving the sky further, I don't want to spend much time at all on this. Can you fork this repository, make your changes, test your changes, and post a pull request?

**Comment by Max-xoxo** [comment]
Sure, if I'll ever get it done. I am not much of a graphical artist myself. If I do attempt it, then I'll definitely test it and pull a request if it looks any better.

My hopes are the sky would look more colourful and vibrant during the night, with my changes.
Although, I need a tiny bit of help. Could you link me to some guide on how to compile the source code to test it in game? I am absolutely clueless on how to do that.

**Comment by ds5678** [comment]
I don't have any links, but you should join the [Discord modding server](https://discord.gg/2mnXAZfGXQ). I'm focused on other projects, so I'm not around very much. However, there are lots of active members.

The general idea of what you need to do is:
1. Open the Unity project with Unity 2019.4.19f1
2. Change the image
3. Build the asset bundle
4. Replace the old asset bundle in the C# project.
5. Open the C# project with Visual Studio 2019 or earlier
6. Compile the C# project
7. Test the mod in-game
8. Possibly return to step 1
